# Generated by Django 4.2.17 on 2024-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('pass_capacity', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
